# Checks for merging PR, linting is currently disabled
name: Integration pipeline
run-name: Integration pipeline triggered by ${{ github.actor }} 

on:
  pull_request:

  workflow_dispatch:
    inputs:
      delivery: 
        description: 'Would you like to update the official image?'
        required: false
        default: true
        type: boolean
      deployment:
        description: 'Would you like to run unit and benchmarking tests?'
        required: false
        default: true
        type: boolean

jobs:
  integration:
    runs-on: self-hosted
    permissions:
      checks: write
      pull-requests: write
    id: integration
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "The name of your branch is ${{ github.head_ref }} and your repository is ${{ github.repository }}."
      
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      
      - name: Print branch
        run: |
          echo "Checked out branch: ${{ github.head_ref }}"

      - name: Show directory contents
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
      
      - name: List files in the repository
        run: |
          echo "github workspace folder"
          ls ${{ github.workspace }}

      - name: Check current directory
        run: pwd

      - name: List files in current directory
        run: ls -la

      - name: List root directory
        run: ls -la /

      - name: List runner's work directory
        run: ls -la /home/runner/work

      - name: List runner's temp directory
        run: ls -la /home/runner/_temp

      - name: List runner's tool directory
        run: ls -la /home/runner/_tool

      - name: List GitHub workspace directory
        run: ls -la ${{ github.workspace }}

      - name: Show environment variables
        run: env

      # - name: Compile
      #   run: |
      #     cd /ros_ws
      #     rosdep install --from-paths src -y --ignore-src
      #     colcon build --packages-select custom_interface
      #     colcon build --packages-select node_test
      #     . install/setup.bash

      # - name: Test run
      #   run: |
      #     ros2 run node_test jetson_node

      # reference the lint pipeline later....
      
      - run: echo ${{ github.event.inputs.delivery }}
      - run: echo ${{ inputs.delivery }}
      - run: echo ${{ github.event.inputs.deployment }}
      - run: echo ${{ inputs.deployment }}

  # These are only triggered through workflow dispatch
  delivery:
    if: ${{ github.event.inputs.delivery }}
    steps:
      - run: echo "this was detected successfully as a boolean (delivery)"
    # uses: ./.github/workflows/delivery.yml
    # with:
    #   branch: {{ github.head_ref }}
    #   deployment: {{ github.events.inputs.deployment }}

  deployment:
    if: ${{ inputs.deployment }}
    steps:
      - run: echo "this was detected successfully as boolean (deployment)"
    # needs: delivery
    # uses: ./.github/workflows/deployment.yml
    # with: 
    #   container_branch: {{ github.head_ref }}
    #   container_version: {{ needs.delivery.outputs.version }}