# runs on any merge, verifies ros2 package can be built, tests run
name: Integration Pipeline
run-name: Integration pipeline triggered by ${{ github.actor }}

on:
  workflow_call:
    inputs:
      delivery:
        required: false
        type: boolean
        default: true
      deployment:
        required: false
        type: boolean
        default: true
  # pull_request:

  workflow_dispatch:
    inputs:
      delivery:
        description: 'Would you like to update the official image?'
        required: false
        default: true
        type: boolean
      deployment:
        description: 'Would you like to run unit and benchmarking tests?'
        required: false
        default: true
        type: boolean
  
jobs:
  inputs:
    - name: Print inputs
      run: | 
        echo ${{ github.event.inputs.delivery }}
        echo ${{ inputs.delivery }}
        echo ${{ github.event.inputs.deployment }}
        echo ${{ inputs.deployment }}

  build:
    - name: Compile
      run: |
        source /opt/ros/humble/setup.bash
        cd /ros2_ws
        rosdep install --from-paths src -y --ignore-src
        colcon build --event-handlers console_cohesion+ --symlink-install

  test:
    - name: Run tests
      needs: build
      run: |
        source /opt/ros/humble/setup.bash
        cd /ros2_ws
        source install/setup.bash
        colcon test --event-handlers console_cohesion+
        colcon test-result --verbose
    # should pipe into markdown and display report...
    
  # These are only triggered through workflow dispatch
  delivery:
    if: ${{ github.event.inputs.delivery }}
    steps:
      - run: echo "this was detected successfully as a boolean (delivery)"
    # uses: ./.github/workflows/delivery.yml
    # with:
    #   branch: {{ github.head_ref }}
    #   deployment: {{ github.events.inputs.deployment }}

  deployment:
    if: ${{ inputs.deployment }}
    steps:
      - run: echo "this was detected successfully as boolean (deployment)"
    # needs: delivery
    # uses: ./.github/workflows/deployment.yml
    # with: 
    #   container_branch: {{ github.head_ref }}
    #   container_version: {{ needs.delivery.outputs.version }}

#     - name: Install dependencies
#       run: |
#         sudo rosdep init
#         rosdep update
#         mkdir -p $ROS_WS/src
#         cp -r $GITHUB_WORKSPACE/* $ROS_WS/src
#         cd $ROS_WS
#         rosdep install --from-paths src --ignore-src -r -y

#     - name: Build packages
#       run: |
#         cd $ROS_WS
#         source /opt/ros/${{ env.ROS_DISTRO }}/setup.sh
#         colcon build --event-handlers console_cohesion+

#     - name: Run tests
#       run: |
#         cd $ROS_WS
#         source install/setup.sh
#         colcon test --event-handlers console_cohesion+
#         colcon test-result --verbose

# # ros2 built tests...