name: ROS Lint Action

on:
  push:
    branches:
      - main  
      - lint
  pull_request:
    branches:
      - main 

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:noble 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up ROS
      uses: ros-tooling/setup-ros@master
      
    - name: Run ROS Lint
      uses: ros-tooling/action-ros-lint@master
      with:
        linter: copyright
        package-name: node_tests  # Replace with your actual package name
