name: ROS LINTER

on:
  push:
    branches:
      - lint 

jobs:
  test_setup_ros:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: '.'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Setup ROS
        uses: ros-tooling/setup-ros@v0.7

      - name: Checkout ament_lint
        uses: actions/checkout@v4
        with:
          repository: ament/ament_lint
          ref: humble
          path: 'ament_lint'

      - name: Install ament_lint dependencies
        run: |
          # Source ROS and setup the environment
          source /opt/ros/humble/setup.bash
          cd ament_lint
          colcon build
          source install/setup.bash

      - name: Try default linter
        working-directory: workspace_cpp/ros2_ws/src/node_test
        run: |
          source /opt/ros/humble/setup.bash
          source ament_lint/install/setup.bash
          ament_lint --package-name ament_copyright ament_lint --workspace-directory ament_lint

      - name: Try a linter with additional arguments
        working-directory: workspace_cpp/ros2_ws/src/node_test
        run: |
          source /opt/ros/humble/setup.bash
          source ament_lint/install/setup.bash
          ament_lint --linter lint_cmake --arguments '--filter=-linelength,+syntax' --package-name ament_cmake_cpplint --workspace-directory ament_lint

      - name: Try a linter with underscores in the name
        working-directory: workspace_cpp/ros2_ws/src/node_test
        run: |
          source /opt/ros/humble/setup.bash
          source ament_lint/install/setup.bash
          ament_lint --linter lint_cmake --arguments '--filter=-linelength' --package-name ament_cmake_cpplint --workspace-directory ament_lint

